# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-01 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EmailUser', '0001_initial'),
        ('strecklista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='strecklista.Group'),
        ),
    ]
