# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailUser', '0004_remove_myuser_is_hedda_hopper'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=70, max_digits=10),
        ),
        migrations.AddField(
            model_name='myuser',
            name='y_chromosome',
            field=models.NullBooleanField(),
        ),
    ]
