# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-30 09:37
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('EmailUser', '0005_auto_20170220_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='protected/avatars/'),
        ),
    ]
