# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strecklista', '0004_registerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerrequest',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='registerrequest',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='email address'),
        ),
    ]
