# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-30 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strecklista', '0005_auto_20170419_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField(max_length=250)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('price', models.TextField(blank=True, max_length=50)),
                ('link', models.URLField(blank=True)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-timestamp',)},
        ),
    ]
